"""Remove unique constraint on telegram_user_id

Revision ID: 816d6af3a400
Revises: 
Create Date: 2025-04-04 12:25:07.478184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '816d6af3a400'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('telegram_user_id', sa.String(length=255), nullable=False),
    sa.Column('amount_in_uah', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_in_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('255', sa.String(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses')
    # ### end Alembic commands ###
